services:
  - type: web
    name: zapcaf
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
